##[pylyzer] failed /home/dani/advent-of-code-2024/day13/venv/lib/python3.12/site-packages/numpy/f2py/__init__.py 1734628981 2503

.__all__: global::List!({"get_include", "run_main"}, 2)
.sys = pyimport "<failure>"
.<failure> = pyimport "<failure>"

.subprocess = pyimport "<failure>"


.os = pyimport "<failure>"


.warnings = pyimport "<failure>"


.___v_desugar_1 = pyimport "exceptions"
.exceptions = pyimport "exceptions"
.VisibleDeprecationWarning: {numpy.exceptions.VisibleDeprecationWarning}
.___v_desugar_2 = pyimport "__init__"
.__init__ = pyimport "__init__"
.f2py2e: Never
.___v_desugar_3 = pyimport "__init__"

.diagnose: Never
.run_main: Never
.main: Never
.get_include: () -> Never
.__getattr__: (attr: Obj) -> Never
.__dir__: () -> global::List!(Never, _: Nat)
