##[pylyzer] failed /home/dani/advent-of-code-2024/day13/venv/lib/python3.12/site-packages/numpy/exceptions.py 1734628981 7838

.__all__: global::List!({"AxisError", "ModuleDeprecationWarning", "TooHardError", "DTypePromotionError", "ComplexWarning", "VisibleDeprecationWarning"}, 6)

._is_loaded: {True}
.ComplexWarning: ClassType
.ComplexWarning <: global::RuntimeWarning

.ModuleDeprecationWarning: ClassType
.ModuleDeprecationWarning <: global::DeprecationWarning

.VisibleDeprecationWarning: ClassType
.VisibleDeprecationWarning <: global::UserWarning

.RankWarning: ClassType
.RankWarning <: global::RuntimeWarning

.TooHardError: ClassType
.TooHardError <: global::RuntimeError

.AxisError: ClassType
.AxisError <: global::ValueError
.AxisError.__call__: (axis: Obj, ndim: Obj := Obj, msg_prefix: Obj := Obj) -> numpy.exceptions.AxisError
.AxisError.__slots__: global::Tuple([{"axis"}, {"ndim"}, {"_msg"}])
.AxisError.__str__: (self: numpy.exceptions.AxisError) -> Never

.DTypePromotionError: ClassType
.DTypePromotionError <: global::TypeError

